import type { Component } from 'svelte';

export type ToolComponentProps = {
	cookieKey: string;
	cookieState: unknown;
};

export interface ToolDefinition {
	title: string;
	description: string;
	href?: string; // autogenerated
	fullscreen?: boolean;
	favicon?: string; // inherit from category if not set
	categoryPath?: string[]; // autogenerated, e.g. ['Development', 'Hashing']

	loadComponent: () => Promise<{
		default: Component<ToolComponentProps>;
	}>;
}

export interface ToolCategory {
	name: string;
	tools: ToolDefinition[];
	subgroups: ToolCategory[];
	favicon?: string;
}
