import type { Component } from 'svelte';

export type ToolComponentProps = {
	cookieKey: string;
	cookieState: unknown;
};

/**
 * Tool components are loaded dynamically from the registry.
 *
 * Some tools declare no props.
 * Some tools require cookieKey/cookieState.
 * The route supplies the runtime props when rendering.
 *
 * Keeping this broad avoids forcing every Tool.svelte file to declare
 * optional cookie props just to satisfy the registry type.
 */
export type ToolComponent = Component<any, any, any>;

export type ToolComponentModule = {
	default: ToolComponent;
};

export interface ToolDefinition {
	title: string;
	description: string;
	href?: string; // Autogenerated by tools-tree.ts
	fullscreen?: boolean;
	removeBorder?: boolean;
	favicon?: string; // Inherits from category if not set
	categoryPath?: string[]; // Autogenerated by tools-tree.ts
	order?: number;
	loadComponent: () => Promise<ToolComponentModule>;
}

export type BuiltToolDefinition = ToolDefinition & {
	href: string;
	categoryPath: string[];
};

export interface ToolCategoryMetadata {
	title: string;
	favicon?: string;
	order?: number;
}

export interface ToolCategory {
	name: string;
	slug?: string; // Autogenerated from folder name
	tools: BuiltToolDefinition[];
	subgroups: ToolCategory[];
	favicon?: string;
	order?: number;
}
